name: Build, Push Docker Image and Refresh ASG

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build dotnet app
        run: |
          dotnet build . --configuration Release

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build docker image and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: "nevetsosu/nevetscotsu:latest"
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Refresh Auto Scaling Group Instances
        run: |
          # Define the Auto Scaling Group name
          asg_name="nevetsCotsu"

          # Start an instance refresh to replace the instances with the latest Docker image
          aws autoscaling start-instance-refresh --auto-scaling-group-name $asg_name --preferences '{"InstanceWarmup": 30, "MinHealthyPercentage": 0}'
